Chang eglobal DB to 'dbw:
NameError: global name 'dbw' is not defined
Supply correct DB variable on connector class object

Change to localhost:
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)
       Use correct localhost

change to password:
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)") (Background on this error at: http://sqlalche.me/e/e3q8)
	use correct password in connector class

change to connector table:
mysql = MySQLConnector(app, 'friendshipZ')
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'friendships'") (Background on this error at: http://sqlalche.me/e/e3q8)
	Use correct table hame.
Change to obj name:
mysql = MySQLConnector(apzp, 'friendship')
Traceback (most recent call last):
  File "server.py", line 6, in <module>
    mysql = MySQLConnector(apzp, 'friendship')
NameError: name 'apzp' is not defined
	Use correct object name in connector call.

Change to querystring:
sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'friendship.usersz' doesn't exist") [SQL: u'SELECT * FROM usersz'] (Background on this error at: http://sqlalche.me/e/f405)
	Use correct query syntax.
